// Generated by npm run generate from spec/server.openapi.json.
/** Production BeeOS Cloud SDK. One install: @beeos-ai/cloud-sdk. Credential is bsk_ only. */

import { createHmac, timingSafeEqual } from "node:crypto";

export type { JSONValue } from "./models.js";
export * from "./models.js";
import type * as Models from "./models.js";
import type { JSONValue } from "./models.js";

export interface HTTPErrorBody { contentType: string; text: string; json?: JSONValue; reason?: string; }

export class BeeOSAPIError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
    readonly requestId?: string,
    readonly body?: Models.APIErrorBody | HTTPErrorBody,
  ) {
    super(message);
    this.name = "BeeOSAPIError";
  }
}

export interface BeeOSClientOptions {
  baseURL: string;
  apiKey: string | (() => string);
  fetch?: typeof fetch;
  externalUserId?: string;
}

type Query = Record<string, string | number | boolean | undefined>;

export class BeeOSClient {
  readonly operations: OperationsModule;
  readonly automations: AutomationsModule;
  readonly audio: AudioModule;
  readonly canvases: CanvasesModule;
  readonly deviceBindings: DeviceBindingsModule;
  readonly a2a: A2aModule;
  readonly harnesses: HarnessesModule;
  readonly responses: ResponsesModule;
  readonly identity: IdentityModule;
  readonly usage: UsageModule;
  readonly catalog: CatalogModule;
  readonly instances: InstancesModule;
  readonly agents: AgentsModule;
  readonly conversations: ConversationsModule;
  readonly messages: MessagesModule;
  readonly tasks: TasksModule;
  readonly files: FilesModule;
  readonly appWebhooks: AppWebhooksModule;
  readonly methods: MethodsModule;

  constructor(private readonly options: BeeOSClientOptions) {
    if (!options.baseURL || !options.apiKey) throw new Error("Server baseURL and bsk_ apiKey are required");
    this.operations = new OperationsModule(this);
    this.automations = new AutomationsModule(this);
    this.audio = new AudioModule(this);
    this.canvases = new CanvasesModule(this);
    this.deviceBindings = new DeviceBindingsModule(this);
    this.a2a = new A2aModule(this);
    this.harnesses = new HarnessesModule(this);
    this.responses = new ResponsesModule(this);
    this.identity = new IdentityModule(this);
    this.usage = new UsageModule(this);
    this.catalog = new CatalogModule(this);
    this.instances = new InstancesModule(this);
    this.agents = new AgentsModule(this);
    this.conversations = new ConversationsModule(this);
    this.messages = new MessagesModule(this);
    this.tasks = new TasksModule(this);
    this.files = new FilesModule(this);
    this.appWebhooks = new AppWebhooksModule(this);
    this.methods = new MethodsModule(this);
  }

  withExternalUser(id: string): BeeOSClient {
    if (!id || id.trim() !== id || id === "." || id === "..") throw new Error("invalid external user id");
    return new BeeOSClient({ ...this.options, externalUserId: id });
  }

  async request<T = JSONValue>(method: string, path: string, init: { query?: Query; json?: JSONValue; idempotencyKey?: string; headers?: Record<string, string>; basePath?: string; responseType?: "sse" | "bytes"; form?: FormData; errorCodeField?: "error" } = {}): Promise<T> {
    const baseURL = init.basePath ? new URL(init.basePath.replace(/\/$/, "") + "/", this.options.baseURL).href : this.options.baseURL;
    const url = new URL(path.replace(/^\//, ""), baseURL.endsWith("/") ? baseURL : baseURL + "/");
    for (const [key, value] of Object.entries(init.query ?? {})) {
      if (value !== undefined) url.searchParams.set(key, String(value));
    }
    const headers: Record<string, string> = {
      Authorization: `Bearer ${typeof this.options.apiKey === "function" ? this.options.apiKey() : this.options.apiKey}`,
      Accept: init.responseType === "sse" ? "text/event-stream" : "application/json",
      ...init.headers,
    };
    if (this.options.externalUserId) headers["X-BeeOS-External-User-ID"] = this.options.externalUserId;
    if (init.idempotencyKey) headers["Idempotency-Key"] = init.idempotencyKey;
    let body: string | FormData | undefined = init.form;
    if (init.json !== undefined) {
      headers["Content-Type"] = "application/json";
      body = JSON.stringify(init.json);
    }
    const fetchImpl = this.options.fetch ?? globalThis.fetch;
    const response = await fetchImpl(url, { method, headers, body });
    const requestId = response.headers.get("X-Request-ID") ?? undefined;
    if (!response.ok) {
      const contentType = response.headers.get("Content-Type") ?? "";
      const text = await response.text();
      let payload: JSONValue;
      try {
        payload = JSON.parse(text) as JSONValue;
      } catch (error) {
        if (!(error instanceof SyntaxError)) throw error;
        throw new BeeOSAPIError(response.status, "invalid_response", response.statusText, requestId, { contentType, text, reason: "invalid_json" });
      }
      let code = "invalid_response";
      let message = response.statusText;
      let body: Models.APIErrorBody | HTTPErrorBody = { contentType, text, json: payload, reason: "invalid_envelope" };
      if (payload !== null && typeof payload === "object" && !Array.isArray(payload)) {
        if (typeof payload.message === "string") message = payload.message;
        const envelope = init.basePath === "/uhp/v1" ? payload.error : payload;
        if (envelope !== null && typeof envelope === "object" && !Array.isArray(envelope)) {
          const candidate = envelope[init.errorCodeField === "error" ? "error" : "code"];
          if (typeof candidate === "string" && candidate.length > 0) {
            code = candidate;
            if (typeof envelope.message === "string") {
              message = envelope.message;
              body = payload as Models.APIErrorBody;
            }
          }
        }
      }
      throw new BeeOSAPIError(response.status, code, message, requestId, body);
    }
    if (response.status === 204) return undefined as T;
    if (init.responseType === "sse") return readEvents(response) as T;
    if (init.responseType === "bytes") return new Uint8Array(await response.arrayBuffer()) as T;
    return await response.json() as T;
  }
}

class IdentityModule {
  constructor(private readonly client: BeeOSClient) {}
  createClientSession(input: Models.CreateClientSessionInput, idempotencyKey: string): Promise<Models.CreateClientSessionResponse> {
    return this.client.request<Models.CreateClientSessionResponse>("POST", "client-sessions", { json: input, idempotencyKey });
  }
  refreshClientSession(sessionId: string, input: Models.RefreshClientSessionInput, idempotencyKey: string): Promise<Models.RefreshClientSessionResponse> {
    return this.client.request<Models.RefreshClientSessionResponse>("POST", `client-sessions/${sessionId}/refresh`, { json: input, idempotencyKey });
  }
  revokeClientSession(sessionId: string, idempotencyKey: string): Promise<Models.RevokeClientSessionResponse> {
    return this.client.request<Models.RevokeClientSessionResponse>("DELETE", `client-sessions/${sessionId}`, { idempotencyKey });
  }
  deleteExternalUser(externalUserId: string, idempotencyKey: string): Promise<Models.DeleteExternalUserResponse> {
    return this.client.request<Models.DeleteExternalUserResponse>("DELETE", `external-users/${externalUserId}`, { idempotencyKey });
  }
  getExternalUserDeletion(externalUserId: string, deletionId: string): Promise<Models.GetExternalUserDeletionResponse> {
    return this.client.request<Models.GetExternalUserDeletionResponse>("GET", `external-users/${externalUserId}/deletions/${deletionId}`);
  }
}

class UsageModule {
  constructor(private readonly client: BeeOSClient) {}
  getSummary(query: Models.GetUsageSummaryQuery): Promise<Models.GetUsageSummaryResponse> {
    return this.client.request<Models.GetUsageSummaryResponse>("GET", "usage/summary", { query });
  }
}

class CatalogModule {
  getDiscovery(): Promise<Models.GetDiscoveryResponse> {
    return this.client.request<Models.GetDiscoveryResponse>("GET", `uhp`, { basePath: "/uhp/v1" });
  }

  constructor(private readonly client: BeeOSClient) {}
  listProviders(query?: Models.ListProvidersQuery): Promise<Models.ListProvidersResponse> {
    return this.client.request<Models.ListProvidersResponse>("GET", "providers", { query });
  }
  listRegions(query?: Models.ListDeployRegionsQuery): Promise<Models.ListDeployRegionsResponse> {
    return this.client.request<Models.ListDeployRegionsResponse>("GET", "deploy/regions", { query });
  }
  listModels(query?: Models.ListDeployModelsQuery): Promise<Models.ListDeployModelsResponse> {
    return this.client.request<Models.ListDeployModelsResponse>("GET", "deploy/models", { query });
  }
  listInstanceTemplates(query?: Models.ListInstanceTemplatesQuery): Promise<Models.ListInstanceTemplatesResponse> {
    return this.client.request<Models.ListInstanceTemplatesResponse>("GET", "instance-templates", { query });
  }
  getInstanceTemplate(id: string): Promise<Models.GetInstanceTemplateResponse> {
    return this.client.request<Models.GetInstanceTemplateResponse>("GET", `instance-templates/${id}`);
  }
  listAgentTemplates(query?: Models.ListAgentTemplatesQuery): Promise<Models.ListAgentTemplatesResponse> {
    return this.client.request<Models.ListAgentTemplatesResponse>("GET", "agent-templates", { query });
  }
  getAgentTemplate(id: string): Promise<Models.GetAgentTemplateResponse> {
    return this.client.request<Models.GetAgentTemplateResponse>("GET", `agent-templates/${id}`);
  }
}

class InstancesModule {
  update(instanceId: string, input: Models.UpdateInstanceMetadataInput, version: number): Promise<Models.UpdateInstanceMetadataResponse> {
    return this.client.request<Models.UpdateInstanceMetadataResponse>("PATCH", `instances/${encodeURIComponent(instanceId)}`, { json: input, headers: { "If-Match": `"${version}"` } });
  }
  start(instanceId: string, idempotencyKey: string, version: number): Promise<Models.StartInstanceResponse> {
    return this.client.request<Models.StartInstanceResponse>("POST", `instances/${encodeURIComponent(instanceId)}/start`, { idempotencyKey, headers: { "If-Match": `"${version}"` } });
  }
  upgrade(instanceId: string, input: Models.UpgradeInstanceInput, idempotencyKey: string): Promise<Models.UpgradeInstanceResponse> {
    return this.client.request<Models.UpgradeInstanceResponse>("POST", `instances/${encodeURIComponent(instanceId)}/upgrade`, { json: input, idempotencyKey });
  }
  getUpgrade(instanceId: string, jobId: string): Promise<Models.GetInstanceUpgradeResponse> {
    return this.client.request<Models.GetInstanceUpgradeResponse>("GET", `instances/${encodeURIComponent(instanceId)}/upgrades/${encodeURIComponent(jobId)}`, {  });
  }
  createTerminalSession(instanceId: string, input: Models.CreateTerminalSessionInput): Promise<Models.CreateTerminalSessionResponse> {
    return this.client.request<Models.CreateTerminalSessionResponse>("POST", `instances/${encodeURIComponent(instanceId)}/terminal-sessions`, { json: input });
  }
  createCanvasSession(instanceId: string, input: Models.CreateCanvasSessionInput): Promise<Models.CreateCanvasSessionResponse> {
    return this.client.request<Models.CreateCanvasSessionResponse>("POST", `instances/${encodeURIComponent(instanceId)}/canvas-sessions`, { json: input });
  }
  exec(instanceId: string, input: Models.ExecInstanceInput): Promise<Models.ExecInstanceResponse> {
    return this.client.request<Models.ExecInstanceResponse>("POST", `instances/${encodeURIComponent(instanceId)}/exec`, { json: input });
  }
  getConnectURL(instanceId: string, query?: Models.GetInstanceConnectURLQuery): Promise<Models.GetInstanceConnectURLResponse> {
    return this.client.request<Models.GetInstanceConnectURLResponse>("GET", `instances/${encodeURIComponent(instanceId)}/connect-url`, { query });
  }
  getStreamURL(instanceId: string, query?: Models.GetInstanceStreamURLQuery): Promise<Models.GetInstanceStreamURLResponse> {
    return this.client.request<Models.GetInstanceStreamURLResponse>("GET", `instances/${encodeURIComponent(instanceId)}/stream-url`, { query });
  }

  constructor(private readonly client: BeeOSClient) {}
  create(input: Models.InstanceCreateInput, idempotencyKey: string): Promise<Models.InstanceCreateResponse> {
    return this.client.request<Models.InstanceCreateResponse>("POST", "instances", { json: input, idempotencyKey });
  }
  list(query?: Models.ListInstancesQuery): Promise<Models.ListInstancesResponse> {
    return this.client.request<Models.ListInstancesResponse>("GET", "instances", { query });
  }
  get(id: string): Promise<Models.GetInstanceResponse> {
    return this.client.request<Models.GetInstanceResponse>("GET", `instances/${id}`);
  }
  getStatus(id: string): Promise<Models.GetInstanceStatusResponse> {
    return this.client.request<Models.GetInstanceStatusResponse>("GET", `instances/${id}/status`);
  }
  stop(id: string, idempotencyKey: string, version: number): Promise<Models.StopInstanceResponse> {
    return this.client.request<Models.StopInstanceResponse>("POST", `instances/${id}/stop`, { json: {}, idempotencyKey, headers: { "If-Match": `"${version}"` } });
  }
  delete(id: string, idempotencyKey: string, version: number): Promise<Models.DeleteInstanceResponse> {
    return this.client.request<Models.DeleteInstanceResponse>("DELETE", `instances/${id}`, { idempotencyKey, headers: { "If-Match": `"${version}"` } });
  }
  open(id: string) {
    return new Instance(this.client, id);
  }
}

class AgentsModule {
  invoke(agentId: string, input: Models.InvokeAgentInput, idempotencyKey: string): Promise<Models.InvokeAgentResponse> {
    return this.client.request<Models.InvokeAgentResponse>("POST", `agents/${encodeURIComponent(agentId)}/invoke`, { json: input, idempotencyKey });
  }

  constructor(private readonly client: BeeOSClient) {}
  list(query?: Models.ListAgentsQuery): Promise<Models.ListAgentsResponse> {
    return this.client.request<Models.ListAgentsResponse>("GET", "agents", { query });
  }
  get(id: string): Promise<Models.GetAgentResponse> {
    return this.client.request<Models.GetAgentResponse>("GET", `agents/${id}`);
  }
  update(id: string, patch: Models.UpdateAgentInput, resourceVersion: number): Promise<Models.UpdateAgentResponse> {
    return this.client.request<Models.UpdateAgentResponse>("PATCH", `agents/${id}`, { json: patch, headers: { "If-Match": `"${resourceVersion}"` } });
  }
}

class ConversationsModule {
  resume(agentId: string, conversationId: string, idempotencyKey: string): Promise<Models.ResumeConversationResponse> {
    return this.client.request<Models.ResumeConversationResponse>("POST", `agents/${encodeURIComponent(agentId)}/conversations/${encodeURIComponent(conversationId)}/resume`, { idempotencyKey });
  }

  constructor(private readonly client: BeeOSClient) {}
  create(agentId: string, input: Models.CreateAgentConversationInput, idempotencyKey: string): Promise<Models.CreateAgentConversationResponse> {
    return this.client.request<Models.CreateAgentConversationResponse>("POST", `agents/${agentId}/conversations`, { json: input, idempotencyKey });
  }
  list(agentId: string, query?: Models.ListAgentConversationsQuery): Promise<Models.ListAgentConversationsResponse> {
    return this.client.request<Models.ListAgentConversationsResponse>("GET", `agents/${agentId}/conversations`, { query });
  }
  get(agentId: string, conversationId: string): Promise<Models.GetConversationResponse> {
    return this.client.request<Models.GetConversationResponse>("GET", `agents/${agentId}/conversations/${conversationId}`);
  }
  update(agentId: string, conversationId: string, input: Models.UpdateConversationInput, version: number): Promise<Models.UpdateConversationResponse> {
    return this.client.request<Models.UpdateConversationResponse>("PATCH", `agents/${agentId}/conversations/${conversationId}`, { json: input, headers: { "If-Match": `"${version}"` } });
  }
  delete(agentId: string, conversationId: string, idempotencyKey: string): Promise<Models.DeleteConversationResponse> {
    return this.client.request<Models.DeleteConversationResponse>("DELETE", `agents/${agentId}/conversations/${conversationId}`, { idempotencyKey });
  }
  cancel(agentId: string, conversationId: string, idempotencyKey: string, input?: JSONValue): Promise<Models.CancelConversationResponse> {
    return this.client.request<Models.CancelConversationResponse>("POST", `agents/${agentId}/conversations/${conversationId}/cancel`, { json: input ?? {}, idempotencyKey });
  }
  clear(agentId: string, conversationId: string, idempotencyKey: string): Promise<Models.ClearConversationResponse> {
    return this.client.request<Models.ClearConversationResponse>("POST", `agents/${agentId}/conversations/${conversationId}/clear`, { idempotencyKey });
  }
  setModel(agentId: string, conversationId: string, modelId: string | null, version: number): Promise<Models.SetConversationModelResponse> {
    return this.client.request<Models.SetConversationModelResponse>("PUT", `agents/${agentId}/conversations/${conversationId}/model`, {
      json: { model_override_id: modelId },
      headers: { "If-Match": `"${version}"` },
    });
  }
}

class MessagesModule {
  createShare(agentId: string, conversationId: string, messageId: string): Promise<Models.CreateShareReplyResponse> {
    return this.client.request<Models.CreateShareReplyResponse>("POST", `agents/${encodeURIComponent(agentId)}/conversations/${encodeURIComponent(conversationId)}/messages/${encodeURIComponent(messageId)}/share`, {  });
  }
  getShare(agentId: string, conversationId: string, messageId: string): Promise<Models.GetShareReplyResponse> {
    return this.client.request<Models.GetShareReplyResponse>("GET", `agents/${encodeURIComponent(agentId)}/conversations/${encodeURIComponent(conversationId)}/messages/${encodeURIComponent(messageId)}/share`, {  });
  }
  revokeShare(agentId: string, conversationId: string, messageId: string): Promise<Models.RevokeShareReplyResponse> {
    return this.client.request<Models.RevokeShareReplyResponse>("DELETE", `agents/${encodeURIComponent(agentId)}/conversations/${encodeURIComponent(conversationId)}/messages/${encodeURIComponent(messageId)}/share`, {  });
  }
  resolveShare(slug: string): Promise<Models.ResolveReplyShareResponse> {
    return this.client.request<Models.ResolveReplyShareResponse>("GET", `reply-shares/${encodeURIComponent(slug)}`, {  });
  }

  constructor(private readonly client: BeeOSClient) {}
  list(agentId: string, conversationId: string, query?: Models.ListConversationMessagesQuery): Promise<Models.ListConversationMessagesResponse> {
    return this.client.request<Models.ListConversationMessagesResponse>("GET", `agents/${agentId}/conversations/${conversationId}/messages`, { query });
  }
  get(agentId: string, conversationId: string, messageId: string): Promise<Models.GetConversationMessageResponse> {
    return this.client.request<Models.GetConversationMessageResponse>("GET", `agents/${agentId}/conversations/${conversationId}/messages/${messageId}`);
  }
}

class TasksModule {
  constructor(private readonly client: BeeOSClient) {}
  create(agentId: string, input: Models.CreateAgentTaskInput, idempotencyKey: string): Promise<Models.CreateAgentTaskResponse> {
    return this.client.request<Models.CreateAgentTaskResponse>("POST", `agents/${agentId}/tasks`, { json: input, idempotencyKey });
  }
  list(agentId: string, query?: Models.ListAgentTasksQuery): Promise<Models.ListAgentTasksResponse> {
    return this.client.request<Models.ListAgentTasksResponse>("GET", `agents/${agentId}/tasks`, { query });
  }
  get(agentId: string, taskId: string): Promise<Models.GetAgentTaskResponse> {
    return this.client.request<Models.GetAgentTaskResponse>("GET", `agents/${agentId}/tasks/${taskId}`);
  }
  listMessages(agentId: string, taskId: string, query?: Models.ListAgentTaskMessagesQuery): Promise<Models.ListAgentTaskMessagesResponse> {
    return this.client.request<Models.ListAgentTaskMessagesResponse>("GET", `agents/${agentId}/tasks/${taskId}/messages`, { query });
  }
  cancel(agentId: string, taskId: string, idempotencyKey: string): Promise<Models.CancelAgentTaskResponse> {
    return this.client.request<Models.CancelAgentTaskResponse>("POST", `agents/${agentId}/tasks/${taskId}/cancel`, { idempotencyKey });
  }
  continueTask(agentId: string, taskId: string, input: Models.ContinueAgentTaskInput, idempotencyKey: string): Promise<Models.ContinueAgentTaskResponse> {
    return this.client.request<Models.ContinueAgentTaskResponse>("POST", `agents/${agentId}/tasks/${taskId}/continue`, { json: input, idempotencyKey });
  }
}

class FilesModule {
  rename(fileId: string, input: Models.RenameFileInput): Promise<Models.RenameFileResponse> {
    return this.client.request<Models.RenameFileResponse>("PATCH", `files/${encodeURIComponent(fileId)}`, { json: input });
  }
  createShare(fileId: string, idempotencyKey: string): Promise<Models.CreateShareFileShareResponse> {
    return this.client.request<Models.CreateShareFileShareResponse>("POST", `files/${encodeURIComponent(fileId)}/share`, { idempotencyKey });
  }
  getShare(fileId: string): Promise<Models.GetShareFileShareResponse> {
    return this.client.request<Models.GetShareFileShareResponse>("GET", `files/${encodeURIComponent(fileId)}/share`, {  });
  }
  revokeShare(fileId: string): Promise<Models.RevokeShareFileShareResponse> {
    return this.client.request<Models.RevokeShareFileShareResponse>("DELETE", `files/${encodeURIComponent(fileId)}/share`, {  });
  }
  resolveShare(slug: string): Promise<Models.ResolveFileShareResponse> {
    return this.client.request<Models.ResolveFileShareResponse>("GET", `file-shares/${encodeURIComponent(slug)}`, {  });
  }
  getSummary(): Promise<Models.GetFilesSummaryResponse> {
    return this.client.request<Models.GetFilesSummaryResponse>("GET", `files/summary`, {  });
  }

  constructor(private readonly client: BeeOSClient) {}
  prepareUpload(input: Models.PresignFileUploadInput, idempotencyKey: string): Promise<Models.PresignFileUploadResponse> {
    return this.client.request<Models.PresignFileUploadResponse>("POST", "files/presign-upload", { json: input, idempotencyKey });
  }
  confirmUpload(fileId: string, input: Models.ConfirmFileUploadInput, idempotencyKey: string): Promise<Models.ConfirmFileUploadResponse> {
    return this.client.request<Models.ConfirmFileUploadResponse>("POST", `files/${fileId}/confirm`, { json: input, idempotencyKey });
  }
  list(query?: Models.ListFilesQuery): Promise<Models.ListFilesResponse> {
    return this.client.request<Models.ListFilesResponse>("GET", "files", { query });
  }
  get(fileId: string): Promise<Models.GetFileResponse> {
    return this.client.request<Models.GetFileResponse>("GET", `files/${fileId}`);
  }
  resolveDownload(fileId: string) {
    return this.client.request("GET", `files/${fileId}`);
  }
  upload(input: Models.PresignFileUploadInput, idempotencyKey: string) {
    return this.prepareUpload(input, idempotencyKey);
  }
  download(fileId: string) {
    return this.resolveDownload(fileId);
  }
  delete(fileId: string, idempotencyKey: string): Promise<Models.DeleteFileResponse> {
    return this.client.request<Models.DeleteFileResponse>("DELETE", `files/${fileId}`, { idempotencyKey });
  }
}

class AppWebhooksModule {
  constructor(private readonly client: BeeOSClient) {}
  verifySvixSignature(rawBody: Uint8Array, headers: Record<string, string>, secret: string, now = Date.now()) {
    return verifySvixWebhookSignature(rawBody, headers, secret, now);
  }
}

function header(headers: Record<string, string>, name: string): string {
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === wanted) return value;
  }
  return "";
}

function timestampAccepted(timestamp: number, now: number): boolean {
  const skew = Math.abs(now / 1000 - timestamp);
  return Number.isFinite(timestamp) && skew <= 300;
}

export function verifyTaskWebhookSignature(rawBody: Uint8Array, headers: Record<string, string>, secret: string, now = Date.now()): boolean {
  if (secret.length < 32 || !header(headers, "X-BeeOS-Event-Id")) {
    throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Task Webhook signature input");
  }
  const parsed = parseVersionedSignature(header(headers, "X-BeeOS-Signature"));
  if (!parsed || !timestampAccepted(parsed.timestamp, now)) {
    throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Task Webhook signature");
  }
  const expected = createHmac("sha256", secret).update(`${parsed.timestamp}.`).update(rawBody).digest();
  for (const signature of parsed.signatures) {
    const actual = Buffer.from(signature, "hex");
    if (actual.length === expected.length && timingSafeEqual(actual, expected)) return true;
  }
  throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Task Webhook signature");
}

export function verifySvixWebhookSignature(rawBody: Uint8Array, headers: Record<string, string>, secret: string, now = Date.now()): boolean {
  const messageId = header(headers, "svix-id");
  const timestampValue = header(headers, "svix-timestamp");
  const signatureValue = header(headers, "svix-signature");
  if (!secret.startsWith("whsec_") || !messageId) {
    throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Svix signature input");
  }
  const timestamp = Number(timestampValue);
  const key = Buffer.from(secret.slice("whsec_".length), "base64");
  if (!timestampAccepted(timestamp, now) || key.length < 16) {
    throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Svix signature");
  }
  const expected = createHmac("sha256", key).update(`${messageId}.${timestampValue}.`).update(rawBody).digest();
  for (const candidate of signatureValue.split(/\s+/)) {
    const [version, value] = candidate.split(",", 2);
    if (version !== "v1" || !value) continue;
    const actual = Buffer.from(value, "base64");
    if (actual.length === expected.length && timingSafeEqual(actual, expected)) return true;
  }
  throw new BeeOSAPIError(401, "invalid_webhook_signature", "invalid Svix signature");
}

function parseVersionedSignature(value: string): { timestamp: number; signatures: string[] } | null {
  let timestamp = 0;
  const signatures: string[] = [];
  for (const part of value.split(",")) {
    const [key, raw] = part.trim().split("=", 2);
    if (!raw) return null;
    if (key === "t") timestamp = Number(raw);
    if (key === "v1") signatures.push(raw);
  }
  return timestamp && signatures.length ? { timestamp, signatures } : null;
}

class MethodsModule {
  constructor(private readonly client: BeeOSClient) {}
  getCapabilities(instanceId: string): Promise<Models.GetRuntimeCapabilitiesResponse> {
    return this.client.request<Models.GetRuntimeCapabilitiesResponse>("GET", `instances/${instanceId}/runtime-capabilities`);
  }
  invoke(instanceId: string, method: string, params: JSONValue, idempotencyKey: string): Promise<Models.InvokeRuntimeMethodResponse> {
    return this.client.request<Models.InvokeRuntimeMethodResponse>("POST", `instances/${instanceId}/methods`, {
      json: { jsonrpc: "2.0", id: idempotencyKey, method, params },
      idempotencyKey,
    });
  }
  readonly agents = {
    create: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "agent/create", params, idempotencyKey),
    update: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "agent/update", params, idempotencyKey),
    delete: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "agent/delete", params, idempotencyKey),
    applyTemplate: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "agent/applyTemplate", params, idempotencyKey),
  };
  readonly skills = {
    list: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "skills/list", params, idempotencyKey),
    install: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "skills/install", params, idempotencyKey),
    update: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "skills/update", params, idempotencyKey),
    uninstall: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "skills/uninstall", params, idempotencyKey),
  };
  readonly models = {
    list: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "models/list", params, idempotencyKey),
  };
  readonly cron = {
    list: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/list", params, idempotencyKey),
    getStatus: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/status", params, idempotencyKey),
    add: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/add", params, idempotencyKey),
    update: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/update", params, idempotencyKey),
    remove: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/remove", params, idempotencyKey),
    run: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/run", params, idempotencyKey),
    listRuns: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "cron/runs", params, idempotencyKey),
  };
  readonly mcp = {
    list: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "mcp/list", params, idempotencyKey),
    set: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "mcp/set", params, idempotencyKey),
    unset: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "mcp/unset", params, idempotencyKey),
  };
  readonly sessions = {
    setMode: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "session/set_mode", params, idempotencyKey),
    setModel: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "session/set_model", params, idempotencyKey),
    clear: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "session/clear", params, idempotencyKey),
    cancel: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "session/cancel", params, idempotencyKey),
  };
  readonly canvas = {
    toggle: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "canvas/toggle", params, idempotencyKey),
    clear: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "canvas/clear", params, idempotencyKey),
    reference: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "canvas/reference", params, idempotencyKey),
    setDimensions: (instanceId: string, params: JSONValue, idempotencyKey: string) => this.invoke(instanceId, "canvas/dimensions", params, idempotencyKey),
  };
}

type C14Call = (params: JSONValue, idempotencyKey: string) => Promise<Models.InvokeRuntimeMethodResponse>;

export class Instance {
  readonly agents: { create: C14Call; update: C14Call; delete: C14Call; applyTemplate: C14Call };
  readonly skills: { list: C14Call; install: C14Call; update: C14Call; uninstall: C14Call };
  readonly models: { list: C14Call };
  readonly cron: { list: C14Call; getStatus: C14Call; add: C14Call; update: C14Call; remove: C14Call; run: C14Call; listRuns: C14Call };
  readonly mcp: { list: C14Call; set: C14Call; unset: C14Call };
  readonly sessions: { setMode: C14Call; setModel: C14Call; clear: C14Call; cancel: C14Call };
  readonly canvas: { toggle: C14Call; clear: C14Call; reference: C14Call; setDimensions: C14Call };

  constructor(private readonly client: BeeOSClient, readonly id: string) {
    const invoke = (method: string): C14Call => (params, idempotencyKey) => this.client.methods.invoke(this.id, method, params, idempotencyKey);
    this.agents = { create: invoke("agent/create"), update: invoke("agent/update"), delete: invoke("agent/delete"), applyTemplate: invoke("agent/applyTemplate") };
    this.skills = { list: invoke("skills/list"), install: invoke("skills/install"), update: invoke("skills/update"), uninstall: invoke("skills/uninstall") };
    this.models = { list: invoke("models/list") };
    this.cron = { list: invoke("cron/list"), getStatus: invoke("cron/status"), add: invoke("cron/add"), update: invoke("cron/update"), remove: invoke("cron/remove"), run: invoke("cron/run"), listRuns: invoke("cron/runs") };
    this.mcp = { list: invoke("mcp/list"), set: invoke("mcp/set"), unset: invoke("mcp/unset") };
    this.sessions = { setMode: invoke("session/set_mode"), setModel: invoke("session/set_model"), clear: invoke("session/clear"), cancel: invoke("session/cancel") };
    this.canvas = { toggle: invoke("canvas/toggle"), clear: invoke("canvas/clear"), reference: invoke("canvas/reference"), setDimensions: invoke("canvas/dimensions") };
  }

  getCapabilities() {
    return this.client.methods.getCapabilities(this.id);
  }
  invoke(method: string, params: JSONValue, idempotencyKey: string) {
    return this.client.methods.invoke(this.id, method, params, idempotencyKey);
  }
}

class OperationsModule {
  constructor(private readonly client: BeeOSClient) {}
  list(instanceId: string, query?: Models.ListRuntimeOperationsQuery): Promise<Models.ListRuntimeOperationsResponse> {
    return this.client.request<Models.ListRuntimeOperationsResponse>("GET", `instances/${encodeURIComponent(instanceId)}/operations`, { query });
  }
  get(operationId: string, instanceId: string): Promise<Models.GetRuntimeOperationResponse> {
    return this.client.request<Models.GetRuntimeOperationResponse>("GET", `instances/${encodeURIComponent(instanceId)}/operations/${encodeURIComponent(operationId)}`, {  });
  }
  cancel(operationId: string, instanceId: string, idempotencyKey: string, XBeeOSOperationId?: string): Promise<Models.CancelRuntimeOperationResponse> {
    return this.client.request<Models.CancelRuntimeOperationResponse>("POST", `instances/${encodeURIComponent(instanceId)}/operations/${encodeURIComponent(operationId)}/cancel`, { idempotencyKey, headers: { ...(XBeeOSOperationId === undefined ? {} : { "X-BeeOS-Operation-Id": XBeeOSOperationId }) } });
  }
}

class AutomationsModule {
  constructor(private readonly client: BeeOSClient) {}
  create(input: Models.CreateAutomationInput): Promise<Models.CreateAutomationResponse> {
    return this.client.request<Models.CreateAutomationResponse>("POST", `automations`, { json: input });
  }
  list(query?: Models.ListAutomationsQuery): Promise<Models.ListAutomationsResponse> {
    return this.client.request<Models.ListAutomationsResponse>("GET", `automations`, { query });
  }
  get(automationId: string): Promise<Models.GetAutomationResponse> {
    return this.client.request<Models.GetAutomationResponse>("GET", `automations/${encodeURIComponent(automationId)}`, {  });
  }
  update(automationId: string, input: Models.UpdateAutomationInput): Promise<Models.UpdateAutomationResponse> {
    return this.client.request<Models.UpdateAutomationResponse>("PATCH", `automations/${encodeURIComponent(automationId)}`, { json: input });
  }
  delete(automationId: string): Promise<Models.DeleteAutomationResponse> {
    return this.client.request<Models.DeleteAutomationResponse>("DELETE", `automations/${encodeURIComponent(automationId)}`, {  });
  }
  pause(automationId: string): Promise<Models.PauseAutomationResponse> {
    return this.client.request<Models.PauseAutomationResponse>("POST", `automations/${encodeURIComponent(automationId)}/pause`, {  });
  }
  resume(automationId: string): Promise<Models.ResumeAutomationResponse> {
    return this.client.request<Models.ResumeAutomationResponse>("POST", `automations/${encodeURIComponent(automationId)}/resume`, {  });
  }
  createRun(automationId: string, input: Models.CreateAutomationRunInput, idempotencyKey: string): Promise<Models.CreateAutomationRunResponse> {
    return this.client.request<Models.CreateAutomationRunResponse>("POST", `automations/${encodeURIComponent(automationId)}/runs`, { json: input, idempotencyKey });
  }
  listRuns(automationId: string, query?: Models.ListAutomationRunsQuery): Promise<Models.ListAutomationRunsResponse> {
    return this.client.request<Models.ListAutomationRunsResponse>("GET", `automations/${encodeURIComponent(automationId)}/runs`, { query });
  }
  getRun(automationId: string, runId: string): Promise<Models.GetAutomationRunResponse> {
    return this.client.request<Models.GetAutomationRunResponse>("GET", `automations/${encodeURIComponent(automationId)}/runs/${encodeURIComponent(runId)}`, {  });
  }
  createWebhook(input: Models.CreateWebhookAutomationInput): Promise<Models.CreateWebhookAutomationResponse> {
    return this.client.request<Models.CreateWebhookAutomationResponse>("POST", `automations/webhooks`, { json: input });
  }
}

class AudioModule {
  constructor(private readonly client: BeeOSClient) {}
  transcribe(input: Models.TranscribeAudioInput): Promise<Models.TranscribeAudioResponse> {
    return this.client.request<Models.TranscribeAudioResponse>("POST", `audio/transcribe`, { form: createForm(input) });
  }
}

class CanvasesModule {
  constructor(private readonly client: BeeOSClient) {}
  getShare(instanceId: string, canvasId: string, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.GetShareCanvasResponse> {
    return this.client.request<Models.GetShareCanvasResponse>("GET", `instances/${encodeURIComponent(instanceId)}/canvases/${encodeURIComponent(canvasId)}/share`, { headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
  createShare(instanceId: string, canvasId: string, input: Models.CreateShareCanvasInput, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.CreateShareCanvasResponse> {
    return this.client.request<Models.CreateShareCanvasResponse>("POST", `instances/${encodeURIComponent(instanceId)}/canvases/${encodeURIComponent(canvasId)}/share`, { json: input, headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
  deleteShare(instanceId: string, canvasId: string, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.DeleteShareCanvasResponse> {
    return this.client.request<Models.DeleteShareCanvasResponse>("DELETE", `instances/${encodeURIComponent(instanceId)}/canvases/${encodeURIComponent(canvasId)}/share`, { headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
  listSnapshots(instanceId: string, canvasId: string, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.ListCanvasSnapshotsResponse> {
    return this.client.request<Models.ListCanvasSnapshotsResponse>("GET", `instances/${encodeURIComponent(instanceId)}/canvases/${encodeURIComponent(canvasId)}/snapshots`, { headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
  restoreSnapshot(instanceId: string, canvasId: string, snapshotId: string, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.RestoreCanvasSnapshotResponse> {
    return this.client.request<Models.RestoreCanvasSnapshotResponse>("POST", `instances/${encodeURIComponent(instanceId)}/canvases/${encodeURIComponent(canvasId)}/snapshots/${encodeURIComponent(snapshotId)}/restore`, { headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
  getSession(instanceId: string, conversationId: string, XBeeOSConversationID: string, XBeeOSPlatformAgentID: string): Promise<Models.GetCanvasSessionResponse> {
    return this.client.request<Models.GetCanvasSessionResponse>("GET", `instances/${encodeURIComponent(instanceId)}/canvas-sessions/${encodeURIComponent(conversationId)}`, { headers: { "X-BeeOS-Conversation-ID": XBeeOSConversationID, "X-BeeOS-Platform-Agent-ID": XBeeOSPlatformAgentID } });
  }
}

class DeviceBindingsModule {
  constructor(private readonly client: BeeOSClient) {}
  getDetails(id: string): Promise<Models.GetAgentBindDetailsResponse> {
    return this.client.request<Models.GetAgentBindDetailsResponse>("GET", `agent/bind/${encodeURIComponent(id)}/details`, { errorCodeField: "error" });
  }
  confirm(id: string, input: Models.ConfirmAgentBindInput): Promise<Models.ConfirmAgentBindResponse> {
    return this.client.request<Models.ConfirmAgentBindResponse>("POST", `agent/bind/${encodeURIComponent(id)}/confirm`, { errorCodeField: "error", json: input });
  }
  createPortal(input: Models.CreatePortalBindInput): Promise<Models.CreatePortalBindResponse> {
    return this.client.request<Models.CreatePortalBindResponse>("POST", `agent/portal/bind-sessions`, { errorCodeField: "error", json: input });
  }
  getPortal(id: string): Promise<Models.GetPortalBindResponse> {
    return this.client.request<Models.GetPortalBindResponse>("GET", `agent/portal/bind-sessions/${encodeURIComponent(id)}`, { errorCodeField: "error" });
  }
  revokePortal(id: string): Promise<Models.RevokePortalBindResponse> {
    return this.client.request<Models.RevokePortalBindResponse>("POST", `agent/portal/bind-sessions/${encodeURIComponent(id)}/revoke`, { errorCodeField: "error" });
  }
  resolvePortal(id: string, input: Models.ResolvePortalBindInput): Promise<Models.ResolvePortalBindResponse> {
    return this.client.request<Models.ResolvePortalBindResponse>("POST", `agent/portal/bind-sessions/${encodeURIComponent(id)}/resolve`, { errorCodeField: "error", json: input });
  }
}

class A2aModule {
  constructor(private readonly client: BeeOSClient) {}
  invoke(agentId: string, input: Models.InvokeA2AInput): Promise<Models.InvokeA2AResponse> {
    return this.client.request<Models.InvokeA2AResponse>("POST", `a2a/${encodeURIComponent(agentId)}`, { json: input });
  }
  getAgentCard(agentId: string): Promise<Models.GetA2AAgentCardResponse> {
    return this.client.request<Models.GetA2AAgentCardResponse>("GET", `a2a/${encodeURIComponent(agentId)}/.well-known/agent-card.json`, {  });
  }
  getAgentCardLegacy(agentId: string): Promise<Models.GetA2AAgentCardLegacyResponse> {
    return this.client.request<Models.GetA2AAgentCardLegacyResponse>("GET", `a2a/${encodeURIComponent(agentId)}/.well-known/agent.json`, {  });
  }
  listTasks(agentId: string, query?: Models.ListA2ATasksQuery): Promise<Models.ListA2ATasksResponse> {
    return this.client.request<Models.ListA2ATasksResponse>("GET", `a2a/${encodeURIComponent(agentId)}/tasks`, { query });
  }
  getTask(agentId: string, taskId: string, query?: Models.GetA2ATaskQuery): Promise<Models.GetA2ATaskResponse> {
    return this.client.request<Models.GetA2ATaskResponse>("GET", `a2a/${encodeURIComponent(agentId)}/tasks/${encodeURIComponent(taskId)}`, { query });
  }
  cancelTask(agentId: string, taskId: string): Promise<Models.CancelA2ATaskResponse> {
    return this.client.request<Models.CancelA2ATaskResponse>("POST", `a2a/${encodeURIComponent(agentId)}/tasks/${encodeURIComponent(taskId)}/cancel`, {  });
  }
}

class HarnessesModule {
  constructor(private readonly client: BeeOSClient) {}
  list(): Promise<Models.ListHarnessesResponse> {
    return this.client.request<Models.ListHarnessesResponse>("GET", `harnesses`, { basePath: "/uhp/v1" });
  }
  get(harness_id: string): Promise<Models.GetHarnessResponse> {
    return this.client.request<Models.GetHarnessResponse>("GET", `harnesses/${encodeURIComponent(harness_id)}`, { basePath: "/uhp/v1" });
  }
  listAllModels(): Promise<Models.ListModelsResponse> {
    return this.client.request<Models.ListModelsResponse>("GET", `models`, { basePath: "/uhp/v1" });
  }
  listModels(harness_id: string): Promise<Models.ListHarnessModelsResponse> {
    return this.client.request<Models.ListHarnessModelsResponse>("GET", `harnesses/${encodeURIComponent(harness_id)}/models`, { basePath: "/uhp/v1" });
  }
}

class ResponsesModule {
  createStream(input: Models.UHPCreateResponseStreamRequest, idempotencyKey?: string): Promise<AsyncIterable<Models.UHPEvent>> {
    return this.client.request<AsyncIterable<Models.UHPEvent>>("POST", "responses", { json: { ...input, stream: true }, idempotencyKey, basePath: "/uhp/v1", responseType: "sse" });
  }

  constructor(private readonly client: BeeOSClient) {}
  create(input: Models.CreateResponseInput, idempotencyKey?: string, UHPVersion?: string): Promise<Models.CreateResponseResponse> {
    return this.client.request<Models.CreateResponseResponse>("POST", `responses`, { json: input, idempotencyKey, headers: { ...(UHPVersion === undefined ? {} : { "UHP-Version": UHPVersion }) }, basePath: "/uhp/v1" });
  }
  get(response_id: string): Promise<Models.GetResponseResponse> {
    return this.client.request<Models.GetResponseResponse>("GET", `responses/${encodeURIComponent(response_id)}`, { basePath: "/uhp/v1" });
  }
  delete(response_id: string): Promise<Models.DeleteResponseResponse> {
    return this.client.request<Models.DeleteResponseResponse>("DELETE", `responses/${encodeURIComponent(response_id)}`, { basePath: "/uhp/v1" });
  }
  getInputItems(response_id: string): Promise<Models.GetResponseInputItemsResponse> {
    return this.client.request<Models.GetResponseInputItemsResponse>("GET", `responses/${encodeURIComponent(response_id)}/input_items`, { basePath: "/uhp/v1" });
  }
  cancel(response_id: string): Promise<Models.CancelResponseResponse> {
    return this.client.request<Models.CancelResponseResponse>("POST", `responses/${encodeURIComponent(response_id)}/cancel`, { basePath: "/uhp/v1" });
  }
  getEvents(response_id: string, LastEventID?: string, UHPVersion?: string): Promise<Models.GetResponseEventsResponse> {
    return this.client.request<Models.GetResponseEventsResponse>("GET", `responses/${encodeURIComponent(response_id)}/events`, { headers: { ...(LastEventID === undefined ? {} : { "Last-Event-ID": LastEventID }), ...(UHPVersion === undefined ? {} : { "UHP-Version": UHPVersion }) }, responseType: 'sse', basePath: "/uhp/v1" });
  }
}

function createForm(input: Record<string, string | number | boolean | Blob | undefined>): FormData {
  const form = new FormData();
  for (const [name, value] of Object.entries(input)) {
    if (value !== undefined) form.append(name, value instanceof Blob ? value : String(value));
  }
  return form;
}

async function* readEvents(response: Response): AsyncGenerator<JSONValue> {
  const reader = response.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  try {
    while (true) {
      const { done, value } = await reader.read();
      buffer = (buffer + decoder.decode(value, { stream: !done })).replace(/\r\n/g, "\n");
      let boundary: number;
      while ((boundary = buffer.indexOf("\n\n")) !== -1) {
        const event = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        const data = event.split("\n").filter(line => line.startsWith("data:")).map(line => line.slice(5).trimStart()).join("\n");
        if (data && data !== "[DONE]") yield JSON.parse(data) as JSONValue;
      }
      if (done) break;
    }
    const data = buffer.split("\n").filter(line => line.startsWith("data:")).map(line => line.slice(5).trimStart()).join("\n");
    if (data && data !== "[DONE]") yield JSON.parse(data) as JSONValue;
  } finally {
    await reader.cancel();
    reader.releaseLock();
  }
}
